# WoolWars Configuration File
# Version: ${project.version}
# Author: CubeCrafter
# Issues:
# Wiki:
# Discord:
license-key: ""
disable-interaction-blocks:
  - CRAFTING_TABLE
  - HOPPER
  - FURNACE
placeable-blocks:
  - GLASS
blocked-commands:
  - spawn
  - msg
chat-format:
  enabled: true
  lobby-format: ""
  waiting-lobby-format: ""
  game-format: ""
  spectator-format: ""
mysql:
  enabled: false
  host: localhost
  port: 3306
  database: woolwars
  username: "username"
  password: "password"
  useSSL: false
lobby-location:

