license-key: ""

disabled-interaction-blocks:
  - CRAFTING_TABLE
  - HOPPER
  - FURNACE

blocked-commands:
  - spawn
  - msg

mysql:
  enabled: false
  host: localhost
  port: 3306
  database: woolwars
  username: "username"
  password: "password"
  useSSL: false

lobby-location:

