# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# | WOOLWARS CONFIGURATION FILE              |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# Version: ${project.version}
# Author: CubeCrafter
# Issues: TODO
# Wiki: TODO
# Discord: TODO

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# | LICENSE KEY                              |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
license-key: "PUT-YOUR-LICENSE-KEY-HERE"

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# | GAME SETTINGS                            |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
enable-leave-command-shortcut: true
starting-countdown: 10
pre-round-duration: 15
active-round-duration: 60
round-over-duration: 5
game-end-duration: 10
disabled-interaction-blocks:
  - CRAFTING_TABLE
  - HOPPER
  - FURNACE
placeable-blocks:
  - COBBLESTONE
disable-fall-damage: true
items:
  play-again-item:
    material: PAPER
    displayname: "&bPlay Again &7(Right-Click)"
    lore:
      - "&7Right-Click to join a new game!"
    slot: 7
  leave-item:
    material: RED_BED
    displayname: "&cReturn to Lobby &7(Right-Click)"
    lose:
      - "&7Right-Click to return to the lobby!"
    slot: 8
  teleporter-item:
    material: COMPASS
    displayname: "&aTeleporter &7(Right-Click)"
    lore:
      - "&7Right-Click to open!"
    slot: 0
jump-pads:
  top-block: SLIME_BLOCK
  bottom-block: STONE
  horizontal-power: 0.5
  vertical-power: 1.0
  particles:
    enabled: true
    type: HAPPY_VILLAGER

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# | CHAT SETTINGS                            |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
blocked-commands:
  whitelist: false
  commands:
    - spawn
    - msg
    - fly
chat-format:
  enabled: true
  lobby-format: "%vault_prefix%{player}: &7{message}"
  waiting-lobby-format: "%vault_prefix%{player}: &7{message}"
  game-format: "{team_color}{team}{player}: &7{message}"
  spectator-format: "&7[Spect]%vault_prefix%{player}: &7{message}"

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# | SOUNDS                                   |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
sounds:
  jump-pad: ENTITY_BAT_TAKEOFF
  round-start: BLOCK_ANVIL_LAND
  round-won: ENTITY_PLAYER_LEVELUP
  round-lost: GHAST_MOAN
  teleport-to-base: ENTITY_ENDERMAN_TELEPORT
  game-won: ENTITY_PLAYER_LEVELUP
  game-lost: GHAST_MOAN
  powerup-collected: ENTITY_EXPERIENCE_ORB_PICKUP
  player-death: GHAST_MOAN
  player-kill: ENTITY_EXPERIENCE_ORB_PICKUP
  countdown: ENTITY_CHICKEN_EGG
  player-joined: ENTITY_CHICKEN_EGG
  player-left: ENTITY_CHICKEN_EGG

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# | SCOREBOARD & NAME TAGS SETTINGS          |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
scoreboard:
  enabled: true
  refresh-interval: 1000
name-tags:
  enabled: true
  prefix: "{team_color}{team_letter} "

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
# | STORAGE SETTINGS                         |
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
mysql:
  enabled: false
  host: localhost
  port: 3306
  database: woolwars
  username: "username"
  password: "password"
  use-ssl: false
lobby-location: ""