name: WoolWars
version: ${project.version}
main: me.cubecrafter.woolwars.WoolWars
api-version: 1.13
description: A fun and unique minigame to play with your friends!
softdepend:
  - PlaceholderAPI
  - Multiverse-Core
commands:
  woolwars:
    description: Main plugin command
    aliases:
      - ww
  leave:
    description: Leave an arena
permissions:
  woolwars.player:
    description: Grant access to all player commands
    children:
      - woolwars.help
      - woolwars.join
      - woolwars.leave
      - woolwars.menu
      - woolwars.stats
      - woolwars.playagain
  woolwars.admin:
    description: Grant access to all admin commands
  woolwars.forcestart:
    description: Force start the game
  woolwars.help:
    description: Show the help menu
  woolwars.join:
    description: Join an arena
  woolwars.leave:
    description: Leave an arena
  woolwars.menu:
    description: Open the game gui
  woolwars.stats:
    description: Open the stats gui
  woolwars.playagain:
    description: Play again